export const iconMap: Record<string, any> = {
  "Bank.png": require("@/assets/icons/Bank.png"),
  "Briefcase.png": require("@/assets/icons/Briefcase.png"),
  "Calender.png": require("@/assets/icons/Calender.png"),
  "Camera.png": require("@/assets/icons/Camera.png"),
  "Car.png": require("@/assets/icons/Car.png"),
  "Cart.png": require("@/assets/icons/Cart.png"),
  "Drink.png": require("@/assets/icons/Drink.png"),
  "Faucet.png": require("@/assets/icons/Faucet.png"),
  "House.png": require("@/assets/icons/House.png"),
  "Island.png": require("@/assets/icons/Island.png"),
  "Mail.png": require("@/assets/icons/Mail.png"),
  "Meal.png": require("@/assets/icons/Meal.png"),
  "Money.png": require("@/assets/icons/Money.png"),
  "Plane.png": require("@/assets/icons/Plane.png"),
  "Popcorn.png": require("@/assets/icons/Popcorn.png"),
  "Question.png": require("@/assets/icons/Question.png"),
  "Utensils.png": require("@/assets/icons/Utensils.png"),
  "Water.png": require("@/assets/icons/Water.png"),
};